baseURL = 'https://labunix.xyz/'
languageCode = 'en-us'
title = 'labunix'
[outputs]
  home = ["HTML", "RSS", "JSON"]
  section = ["HTML", "RSS"]
[params]
  mainSections = ["posts"]
[params.logo]
  logoText = "labunix"
  logoHomeLink = "/"
[languages]
  [languages.en]
    languageName = "English"
    title = "labunix"
    weight = 1

    [languages.en.params]
      subtitle = "ad hoc unix notes"
      owner = "lukas"

    [languages.en.menu]
      [[languages.en.menu.main]]
        identifier = "about"
        name = "about/"
        url = "/about/"
        weight = 2
      [[languages.en.menu.main]]
        identifier = "rss"
        name = "rss/"
        url = "/posts/index.xml"
        weight = 99
[privacy]
  [privacy.youTube]
    privacyEnhanced = true
[markup.goldmark.renderer]
  unsafe = true
[taxonomies]
  category = "categories"
  tag = "tags"
