server {
    listen 127.0.0.1:8089;
    listen [::1]:8089;
    server_name _;

    root /srv/www/labunix/public;
    index index.html;

    access_log /var/log/nginx/labunix-i2p.access.log;
    error_log  /var/log/nginx/labunix-i2p.error.log;

    location / {
        try_files $uri $uri/ =404;
    }
}
