services:
  db:
    image: postgres:16-alpine
    container_name: healthchecks-db
    restart: unless-stopped
    environment:
      POSTGRES_DB: healthchecks
      POSTGRES_USER: healthchecks
      POSTGRES_PASSWORD: 1qwh81mvBWygdk1tGifsEohxMx6g4C+Wma/+o/HCqX5e8hRt4ZZl4czQp/kg3r/O
    volumes:
      - ./db:/var/lib/postgresql/data

  web:
    image: healthchecks/healthchecks:latest
    container_name: healthchecks
    restart: unless-stopped
    depends_on:
      - db
    environment:
      DB: postgres
      DB_HOST: db
      DB_NAME: healthchecks
      DB_USER: healthchecks
      DB_PASSWORD: 1qwh81mvBWygdk1tGifsEohxMx6g4C+Wma/+o/HCqX5e8hRt4ZZl4czQp/kg3r/O
      SECRET_KEY: c0ce83cb5201c6c85410ccb02bfa915b33b1b40e97612bd84e1b5ff7076063a2
      SITE_ROOT: http://10.50.0.1:8002
      ALLOWED_HOSTS: 10.50.0.1,localhost,127.0.0.1
      REGISTRATION_OPEN: "False"
    ports:
      - "10.50.0.1:8002:8000"
    volumes:
      - ./data:/var/lib/healthchecks
