services:
  searxng:
    image: searxng/searxng:latest
    sysctls:
      - net.ipv6.conf.all.disable_ipv6=1
    container_name: searxng
    logging:
      driver: "none"
    restart: unless-stopped
    ports:
      - "10.50.0.1:8080:8080"
    volumes:
      - ./:/etc/searxng:rw
    environment:
      - SEARXNG_BASE_URL=http://10.50.0.1:8080/

