services:
  privatebin:
    image: privatebin/nginx-fpm-alpine:latest
    container_name: privatebin
    restart: unless-stopped
    read_only: true
    environment:
      - TZ=Europe/Warsaw
    ports:
      - "127.0.0.1:8081:8080"
    volumes:
      - ./data:/srv/data
      - ./cfg/conf.php:/srv/cfg/conf.php:ro
    tmpfs:
      - /tmp
      - /var/tmp
    networks:
      - web

networks:
  web:
    driver: bridge

