services:
  vaultwarden:
    image: vaultwarden/server:latest
    container_name: vaultwarden
    restart: unless-stopped
    ports:
      - "127.0.0.1:9081:80"
      - "127.0.0.1:3012:3012"
    volumes:
      - /srv/vaultwarden:/data
    env_file: vaultwarden.env
