[Interface]
PrivateKey = <REDACTED>
Address = 10.50.0.2/24
DNS = 9.9.9.9

[Peer]
PublicKey = 5XQ7zYqOsQuDfDPxDn4d5l4xNQfpMNnX2DWeS9iM5DA=
Endpoint = vpn.labunix.xyz:9443
AllowedIPs = 0.0.0.0/0, ::/0
PersistentKeepalive = 25

