[Interface]
Address = 10.50.0.1/24
ListenPort = 52220
PrivateKey = <REDACTED>
MTU = 1280

[Peer] # pixel
PublicKey =  3EY/TzajRidy65+kmGRYQ+/+63vhfFicUrpWbywobms=
AllowedIPs = 10.50.0.2/32

[Peer] # debian host
PublicKey = Dq8XOr5UvISRWNcETEOdkoGzf2dpMKZGNI0v7n+j6XE=
AllowedIPs = 10.50.0.3/32

[Peer] # adam 
PublicKey =  5XQ7zYqOsQuDfDPxDn4d5l4xNQfpMNnX2DWeS9iM5DA=
AllowedIPs = 10.50.0.4/32

