# renew_before_expiry = 30 days
version = 4.0.0
archive_dir = /etc/letsencrypt/archive/voice.labunix.xyz
cert = /etc/letsencrypt/live/voice.labunix.xyz/cert.pem
privkey = /etc/letsencrypt/live/voice.labunix.xyz/privkey.pem
chain = /etc/letsencrypt/live/voice.labunix.xyz/chain.pem
fullchain = /etc/letsencrypt/live/voice.labunix.xyz/fullchain.pem

# Options used in the renewal process
[renewalparams]
account = a1413eee8d5f0cd07eadb7e29d2cc032
authenticator = dns-cloudflare
server = https://acme-v02.api.letsencrypt.org/directory
key_type = ecdsa
dns_cloudflare_propagation_seconds = 30
dns_cloudflare_credentials = /etc/letsencrypt/cloudflare/credentials.ini
